# =========================================
# ACTIVE PROFILE
# =========================================
spring.profiles.active=prod


# =========================================
# DATABASE (Render PostgreSQL)
# =========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# =========================================
# RABBITMQ (CloudAMQP)
# =========================================
spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}


# =========================================
# SERVER (Render assigns PORT automatically)
# =========================================
server.port=${PORT:8080}